apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-dhjybowv
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-dhjybowv:4b706b95a5d1209447e908d406f1ecdb243a1972@sha256:3a1e846431d6c390861309573659e10d8685821455e63f9b3f2e944e62cbb7c4
        name: container-image  
